/**
 * #8 — KNOWLEDGE DISTILLATION MARKETPLACE
 * ═══════════════════════════════════════════════════════════════════
 * Teacher model locked on Shelby (private, never revealed).
 * Student sends input samples → teacher generates soft labels → labels stored on Shelby.
 * Student trains on soft labels without ever seeing teacher weights.
 * ShelbyUSD payment per distillation job.
 *
 * Why this is novel:
 * - Teacher IP protected: weights never leave Shelby
 * - Student gets knowledge (soft labels) not weights
 * - On-chain payment settlement (ShelbyUSD per job)
 * - Cryptographic proof: these labels came from THIS teacher (SHA-256 binding)
 * - First decentralized knowledge distillation marketplace
 *
 * Nobody has built this on Shelby.
 *
 * Flow:
 * 1. Teacher registers model on Provenode
 * 2. Teacher sets price per distillation job
 * 3. Student creates job: uploads input samples to Shelby
 * 4. Provenode routes request to teacher's inference endpoint
 * 5. Soft labels returned, stored on Shelby
 * 6. Student downloads soft labels, trains locally
 * 7. ShelbyUSD transferred on Aptos
 */
import { createHash, createHmac } from 'node:crypto';

/**
 * Build a distillation job record.
 */
export function buildDistillationJob({
  studentId, teacherModelId, teacherSha256,
  inputObjectId, pricePerSample, sampleCount,
}) {
  const jobId = createHash('sha256')
    .update(`${studentId}:${teacherModelId}:${Date.now()}`)
    .digest('hex')
    .slice(0, 16);

  return {
    id: jobId,
    studentId,
    teacherModelId,
    teacherSha256,
    inputObjectId,    // Shelby URL to student's input samples
    outputObjectId: null, // Shelby URL to soft labels (filled when complete)
    sampleCount,
    pricePerSample,   // in ShelbyUSD
    totalPrice: sampleCount * pricePerSample,
    status: 'pending',
    createdAt: new Date().toISOString(),
    completedAt: null,
  };
}

/**
 * Build a soft label record — the actual distillation output.
 * Stored on Shelby as a JSON blob.
 *
 * Soft labels are the teacher's probability distribution over classes
 * (not just the argmax). Much richer signal for student training.
 *
 * Format per sample:
 * { inputHash, softLabels: [0.02, 0.91, 0.04, ...], temperature: 4.0, topK: [-1, 2, 5, ...] }
 */
export function buildSoftLabelRecord({ jobId, teacherModelId, teacherSha256, samples, temperature = 4.0 }) {
  const labelManifest = samples.map(s => ({
    inputHash: createHash('sha256').update(JSON.stringify(s.input)).digest('hex'),
    // Soft labels at temperature T — teacher logits / T then softmax
    softLabels: s.logits || s.softLabels || [],
    temperature,
    topClassIndex: s.topClass,
    confidence: s.confidence,
  }));

  // Binding signature: these labels came from THIS teacher model
  const bindingHash = createHash('sha256')
    .update(teacherSha256 + labelManifest.map(l => l.inputHash).join(':'))
    .digest('hex');

  return {
    jobId,
    teacherModelId,
    teacherSha256,
    temperature,
    sampleCount: samples.length,
    labels: labelManifest,
    bindingHash, // Proves labels came from teacherSha256
    generatedAt: new Date().toISOString(),
  };
}

/**
 * Verify that a soft label blob was generated by a specific teacher model.
 * Student calls this before training to ensure labels are authentic.
 */
export function verifyDistillationLabels(labelRecord, expectedTeacherSha256) {
  if (labelRecord.teacherSha256 !== expectedTeacherSha256) {
    return { valid: false, reason: 'Teacher SHA-256 mismatch' };
  }

  const expectedBinding = createHash('sha256')
    .update(labelRecord.teacherSha256 + labelRecord.labels.map(l => l.inputHash).join(':'))
    .digest('hex');

  return {
    valid: expectedBinding === labelRecord.bindingHash,
    teacherModelId: labelRecord.teacherModelId,
    sampleCount: labelRecord.sampleCount,
    temperature: labelRecord.temperature,
    reason: expectedBinding === labelRecord.bindingHash ? 'Valid' : 'Binding hash mismatch',
  };
}

/**
 * Calculate KL divergence between student and teacher distributions.
 * Measures how well the student is learning from the teacher.
 * Lower = better.
 */
export function klDivergence(studentProbs, teacherProbs) {
  let kl = 0;
  for (let i = 0; i < teacherProbs.length; i++) {
    const p = teacherProbs[i];
    const q = studentProbs[i] || 1e-10;
    if (p > 0) kl += p * Math.log(p / q);
  }
  return kl;
}
